# Generated by Django 4.1.6 on 2023-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_rename_uservacationdetails_uservacation"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationslot",
            name="slot_type",
            field=models.IntegerField(default=0),
        ),
    ]
