# Generated by Django 4.1.6 on 2023-04-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_vacationslot_slot_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="uservacation", name="slots",),
        migrations.AddField(
            model_name="uservacation",
            name="slots",
            field=models.TextField(blank=True, null=True),
        ),
    ]
